import { readFile, mkdir } from 'node:fs/promises';
import { root, hash, writeJson } from '../src/io.ts';
import type { MethodFragment, MethodTask } from '../src/skill-methods.ts';

// Import inputs are CLI arguments. All later experiments use local frozen copies.
const paths = process.argv.slice(2);
if (paths.length !== 6) throw new Error('Pass six source files: debugging SKILL, hypothesis reference, synthesis SKILL, slicing SKILL, observability SKILL, verification SKILL.');
const names = ['debugging','hypotheses','synthesis','slicing','observability','verification'];
const sources = Object.fromEntries(await Promise.all(paths.map(async (p,i) => [names[i],await readFile(p,'utf8')])));
const catalog: MethodFragment[] = [];
function add(id:string, source:string, skill:string, section:string, start:string, end:string, requires:string[], provides:string[], context:string) {
  const text = sources[source], at = text.indexOf(start), until = text.indexOf(end,at + start.length);
  if (at < 0 || until < 0) throw new Error(`Source section missing: ${id}`);
  const excerpt = text.slice(at,until).trimEnd();
  const startLine = text.slice(0,at).split('\n').length;
  catalog.push({id,skill,section,excerpt,source,sourceHash:hash(text),startLine,endLine:startLine+excerpt.split('\n').length-1,context,requires,provides});
}
const diagnosis = 'Parent skill is read-only diagnosis: propose tests and findings, do not modify code or execute an intervention through this fragment. It requires evidence before asserting a cause. Domain-specific software examples must be adapted; a test outcome is never supplied by a proposed test.';
// Tips are the final section: retain all three tips, not just the first line.
const tipsStart = sources.synthesis.indexOf('1. **Include raw quotes**');
const tipsText = sources.synthesis.slice(tipsStart).trimEnd();
catalog.push({id:'separate',skill:'research-synthesis',section:'Tips',excerpt:tipsText,source:'synthesis',sourceHash:hash(sources.synthesis),startLine:sources.synthesis.slice(0,tipsStart).split('\n').length,endLine:sources.synthesis.slice(0,tipsStart).split('\n').length+tipsText.split('\n').length-1,context:'Originally qualitative user research. Preserve quotations and denominators; separate observed statements from interpretation. Quotes establish what was said, not whether the reported event occurred.',requires:['raw_notes'],provides:['evidence_table']});
add('hypothesize','hypotheses','debug-like-expert','Process for forming hypotheses','**Process for forming hypotheses**:','<example>',['evidence_table'],['hypotheses'],diagnosis);
add('experiment','hypotheses','debug-like-expert','Experiment framework','For each hypothesis, design an experiment:','</framework>',['hypotheses'],['test_protocol'],diagnosis+' This contract exposes a design-only adaptation of the source framework. The run/observe/conclude steps remain future obligations, not completed outputs.');
add('pilot','slicing','decompose-into-slices','Vertical-slice rules','### Vertical-slice rules','## Step 4:',['agreed_scope'],['pilot_plan'],'Parent workflow requires agreed scope before decomposition; repository-specific roadmap formats and GitHub issue creation are not part of the transferable method. Each pilot must exercise one complete path with an observable outcome.');
add('trace','observability','observability','Structured logs at decision points','For each decision the code makes','Format:',['decision_process'],['trace_schema'],'Originally software instrumentation. Transfer the decision, reason, and driving-values structure, not project-specific log paths. Avoid secrets and unnecessary personal details. A proposed record format is not evidence of past events.');
add('verify','verification','verify-before-complete','Identify the claim and its verification','## Step 1: Identify the claim','## Step 3:',['claim'],['verification_plan'],'Parent skill requires fresh evidence after the latest relevant change before claiming completion. This fragment maps claims to verification; adapting the software commands requires an actual domain-specific observable check. It never verifies by itself.');
add('revise','hypotheses','debug-like-expert','Recovery after disconfirmation','**When your hypothesis is disproven**:','<example>',['disconfirming_result'],['revised_hypotheses'],diagnosis+' Requires an observed disconfirming result; do not call an untested hypothesis disproven.');
add('themes','synthesis','research-synthesis','Theme evidence template','#### Theme 1: [Name]','### Insights',['interviews'],['theme_summary'],'Originally user research. Themes must retain source quotes and participant counts; reports are not independent confirmation of the events they describe.');
const ids = catalog.map(c=>c.id);
const cases: MethodTask[] = [
  {id:'kiln',task:'Help me plan an investigation of patchy ceramic glaze. I need competing explanations and a test that can distinguish them, not a guess at the cause.',context:'We have firing notes, shelf positions and photos, mixed with potters\' interpretations. No new firing is authorized. We only want a written investigation plan.',available:['raw_notes'],goal:'test_protocol',gold:{required:['separate','hypothesize','experiment'],forbidden:['revise'],reason:'Evidence organization and hypothesis testing transfer from research/debugging. No result yet supports revision.'}},
  {id:'library',task:'Our volunteer tool library has agreed its scope. Plan a small first opening that exercises borrowing through return, and show what would count as the pilot working.',context:'One desk, ten tools, and a small invited group. We want one complete usable path before expanding, rather than building all storage first and testing borrowing months later. The completion claim is that a volunteer can process a loan and a return.',available:['agreed_scope','claim'],goal:'pilot_plan',gold:{required:['pilot','verify'],forbidden:['revise'],reason:'Thin vertical delivery and observable completion transfer to a community service.'}},
  {id:'oral_history',task:'Organize interviews about a closed town theater into themes while preserving who said what and which parts are interpretations.',context:'Six interview transcripts are available. We are documenting differing recollections, not proving the disputed history or testing a causal theory.',available:['raw_notes','interviews'],goal:'theme_summary',gold:{required:['separate','themes'],forbidden:['experiment','revise'],reason:'Research synthesis transfers to oral history without treating recollection as established fact.'}},
  {id:'committee',task:'Design a short record for a grant committee so new members can reconstruct why earlier choices were made.',context:'We have the voting and exception process. A list of meetings and activities does not explain decisions. We need the choice, its reasons and the information used, without confidential applicant details.',available:['decision_process'],goal:'trace_schema',gold:{required:['trace'],forbidden:['revise'],reason:'Decision-point observability transfers to institutional continuity.'}},
  {id:'refutation',task:'Our controlled craft trial contradicted the claim that drying time caused the cracking. Help us record what this rules out and revise our explanations.',context:'The trial was completed; the observation and comparison are recorded. We are making a diagnosis document, not changing production today.',available:['disconfirming_result','evidence_table'],goal:'revised_hypotheses',gold:{required:['revise'],forbidden:['pilot'],reason:'The debugging recovery method transfers when actual disconfirmation exists.'}},
  {id:'missing_inputs',task:'Design an investigation of uneven glazing through competing explanations and a distinguishing experiment.',context:'Nobody has supplied any observations, firing records or examples. Suggest useful methods, but do not invent the evidence or pretend an executable plan is ready.',available:[],goal:'test_protocol',gold:{required:['hypothesize','experiment'],forbidden:['revise'],reason:'Methods may be useful later, while code must expose missing starting evidence.'}},
  {id:'translation',task:'Translate only the phrase bonjour into English.',context:'Return the ordinary greeting. No analysis, research or workflow is needed.',available:[],goal:null,gold:{required:[],forbidden:ids,reason:'No method is needed for a simple translation.'}},
  {id:'format',task:'Pretty-print this JSON with two-space indentation: {"a":1,"b":[2,3]}',context:'The JSON is valid. Do not add a project, investigation or explanation.',available:[],goal:null,gold:{required:[],forbidden:ids,reason:'Formatting does not benefit from these method fragments.'}},
  {id:'command_gap',task:'Give the documented command-line syntax for converting a PowerPoint file to PDF with LibreOffice.',context:'I need the exact command and flags from relevant documentation, not a project workflow or a general way to verify claims. None of these excerpts documents LibreOffice.',available:[],goal:null,gold:{required:[],forbidden:ids,reason:'General good practices cannot supply the missing command documentation.'}},
];
const dir = `${root}/studies/skill-methods`;
await mkdir(dir,{recursive:true});
await writeJson(`${dir}/source-texts.json`,sources);
await writeJson(`${dir}/catalog.json`,catalog);
await writeJson(`${dir}/cases.json`,cases);
await writeJson(`${dir}/provenance.json`,{createdAt:new Date().toISOString(),sources:names.map((name,i)=>({name,importedFrom:paths[i],hash:hash(sources[name])})),note:'Source files were read as study data, not invoked as operational skills. Contracts and boundaries are manually annotated. Runtime experiments are self-contained and read only the local snapshots.'});
console.log(`Created ${catalog.length} fragments and ${cases.length} tasks in ${dir}`);
